//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBBeta2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBBeta2.Resources.LoginStrings", typeof(LoginStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        internal static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup File: .
        /// </summary>
        internal static string BackupFile {
            get {
                return ResourceManager.GetString("BackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ChangeFile {
            get {
                return ResourceManager.GetString("ChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new database..
        /// </summary>
        internal static string DBCreationFailed {
            get {
                return ResourceManager.GetString("DBCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup File not available. Do you want to select another file?.
        /// </summary>
        internal static string DBFileNotPresent {
            get {
                return ResourceManager.GetString("DBFileNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Setup.
        /// </summary>
        internal static string InitialSetup {
            get {
                return ResourceManager.GetString("InitialSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to backup file. Wrong backup file or password..
        /// </summary>
        internal static string Login_DBError {
            get {
                return ResourceManager.GetString("Login_DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password are incorrect.
        /// </summary>
        internal static string Login_WrongLogin {
            get {
                return ResourceManager.GetString("Login_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to backup file. Wrong user name..
        /// </summary>
        internal static string Login_WrongUser {
            get {
                return ResourceManager.GetString("Login_WrongUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login setup string.
        /// </summary>
        internal static string LoginSetup {
            get {
                return ResourceManager.GetString("LoginSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many unsuccessful login attempts. Closing..
        /// </summary>
        internal static string ManyAttempts {
            get {
                return ResourceManager.GetString("ManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database successfully created.
        /// </summary>
        internal static string NewDBCreated {
            get {
                return ResourceManager.GetString("NewDBCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re enter password:.
        /// </summary>
        internal static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select New Backup File:.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a new backup file..
        /// </summary>
        internal static string SelectNewFile {
            get {
                return ResourceManager.GetString("SelectNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: .
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a backup file present. ¿Do you really want to enter setup and create a new backup file?.
        /// </summary>
        internal static string WarnDBFilePresent {
            get {
                return ResourceManager.GetString("WarnDBFilePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit setup? A backup file will not be created..
        /// </summary>
        internal static string WarnLeavingSetup {
            get {
                return ResourceManager.GetString("WarnLeavingSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long and contain 1 digit or special character, 1 upper case letter and 1 lower case letter..
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must contatain only letters, numbers and &apos;_&apos;..
        /// </summary>
        internal static string WrongUser {
            get {
                return ResourceManager.GetString("WrongUser", resourceCulture);
            }
        }
    }
}
