//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBBeta2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MBStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MBStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBBeta2.Resources.MBStrings", typeof(MBStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select options and dates to refine search results.
        /// </summary>
        internal static string AdvancedSearchHeader {
            get {
                return ResourceManager.GetString("AdvancedSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup of your data.
        /// </summary>
        internal static string BackupData {
            get {
                return ResourceManager.GetString("BackupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed backup files (*.zip)|*.zip.
        /// </summary>
        internal static string BackupFiles {
            get {
                return ResourceManager.GetString("BackupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed backup files (*.zip)|*.zip|All files (*.*)|*.*.
        /// </summary>
        internal static string BackupFilesAllFiles {
            get {
                return ResourceManager.GetString("BackupFilesAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Period Selected.
        /// </summary>
        internal static string BackupPeriod {
            get {
                return ResourceManager.GetString("BackupPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup range.
        /// </summary>
        internal static string BackupRange {
            get {
                return ResourceManager.GetString("BackupRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Status.
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Your Network.
        /// </summary>
        internal static string BrowseNetwork {
            get {
                return ResourceManager.GetString("BrowseNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Select your friends or groups..
        /// </summary>
        internal static string BrowseSelectFriends {
            get {
                return ResourceManager.GetString("BrowseSelectFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Select what you want to see..
        /// </summary>
        internal static string BrowseSelectOptions {
            get {
                return ResourceManager.GetString("BrowseSelectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected mode.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in Facebook.
        /// </summary>
        internal static string ConnectedFB {
            get {
                return ResourceManager.GetString("ConnectedFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current View.
        /// </summary>
        internal static string CurrentView {
            get {
                return ResourceManager.GetString("CurrentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Advanced Search Options.
        /// </summary>
        internal static string DisableAdvancedSearch {
            get {
                return ResourceManager.GetString("DisableAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected mode.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in FB.
        /// </summary>
        internal static string DisconnectedFB {
            get {
                return ResourceManager.GetString("DisconnectedFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click To.
        /// </summary>
        internal static string DoubleClickTo {
            get {
                return ResourceManager.GetString("DoubleClickTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced Search Options.
        /// </summary>
        internal static string EnableAdvancedSearch {
            get {
                return ResourceManager.GetString("EnableAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string FBEvents {
            get {
                return ResourceManager.GetString("FBEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string FBMessages {
            get {
                return ResourceManager.GetString("FBMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Albums.
        /// </summary>
        internal static string FBPhotoAlbums {
            get {
                return ResourceManager.GetString("FBPhotoAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string FBPhotos {
            get {
                return ResourceManager.GetString("FBPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Posts.
        /// </summary>
        internal static string FBWall {
            get {
                return ResourceManager.GetString("FBWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Options.
        /// </summary>
        internal static string FilterOptions {
            get {
                return ResourceManager.GetString("FilterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string FriendFilterClearSelection {
            get {
                return ResourceManager.GetString("FriendFilterClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string FriendFilterSelectAll {
            get {
                return ResourceManager.GetString("FriendFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string FriendFilterShow {
            get {
                return ResourceManager.GetString("FriendFilterShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Friends.
        /// </summary>
        internal static string FriendFilterShowAll {
            get {
                return ResourceManager.GetString("FriendFilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Friends.
        /// </summary>
        internal static string FriendFilterShowSelected {
            get {
                return ResourceManager.GetString("FriendFilterShowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: .
        /// </summary>
        internal static string FriendFilterText {
            get {
                return ResourceManager.GetString("FriendFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update:.
        /// </summary>
        internal static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string LIMessages {
            get {
                return ResourceManager.GetString("LIMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string LIPosts {
            get {
                return ResourceManager.GetString("LIPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your social network accounts and define your user profiles..
        /// </summary>
        internal static string LoginOptions {
            get {
                return ResourceManager.GetString("LoginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members....
        /// </summary>
        internal static string Main_Members {
            get {
                return ResourceManager.GetString("Main_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Date Filter.
        /// </summary>
        internal static string NavigateDateFilter {
            get {
                return ResourceManager.GetString("NavigateDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Your Network Updates.
        /// </summary>
        internal static string NavigateNetwork {
            get {
                return ResourceManager.GetString("NavigateNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Updated.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of posts to show:.
        /// </summary>
        internal static string NumberOfRecords {
            get {
                return ResourceManager.GetString("NumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Older Publications.
        /// </summary>
        internal static string OlderPublications {
            get {
                return ResourceManager.GetString("OlderPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Link....
        /// </summary>
        internal static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person like this..
        /// </summary>
        internal static string PersonLikeThis {
            get {
                return ResourceManager.GetString("PersonLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to persons like this..
        /// </summary>
        internal static string PersonsLikeThis {
            get {
                return ResourceManager.GetString("PersonsLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your search term.
        /// </summary>
        internal static string SearchHeader {
            get {
                return ResourceManager.GetString("SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Your Network.
        /// </summary>
        internal static string SearchNetwork {
            get {
                return ResourceManager.GetString("SearchNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results For:.
        /// </summary>
        internal static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the name for the backup file.
        /// </summary>
        internal static string SelectBackupName {
            get {
                return ResourceManager.GetString("SelectBackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string TwPhotos {
            get {
                return ResourceManager.GetString("TwPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets.
        /// </summary>
        internal static string TwTweets {
            get {
                return ResourceManager.GetString("TwTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a backup from your data.
        /// </summary>
        internal static string Unzip {
            get {
                return ResourceManager.GetString("Unzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details....
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details Of.
        /// </summary>
        internal static string ViewDetailsOf {
            get {
                return ResourceManager.GetString("ViewDetailsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results....
        /// </summary>
        internal static string ViewResults {
            get {
                return ResourceManager.GetString("ViewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you thinking?.
        /// </summary>
        internal static string WhatAreYouThinking {
            get {
                return ResourceManager.GetString("WhatAreYouThinking", resourceCulture);
            }
        }
    }
}
