CREATE TABLE [PersonData](
	[PartitionDate] [numeric](8) NOT NULL,
	[PartitionID] [int] NOT NULL,
	[PersonID] [int] NOT NULL,
  [SocialNetwork] [int] NOT NULL,
  [SNID] [string] NOT NULL,
	[Active] [bit] NOT NULL,
  [Distance] [int] NULL,
	[LastUpdate] [datetime] NOT NULL,
	[PreviousDate] [numeric](8, 0) NULL,
	[PreviousID] [int] NULL,
	[ProfilePic] [nvarchar](255) NULL,
	[Link] [nvarchar](255) NULL,
	[UpdatedInSN] [datetime] NULL,
	[FirstName] [nvarchar](255) NULL,
	[MiddleName] [nvarchar](255) NULL,
	[LastName] [nvarchar](255) NULL,
	[BirthDay] [tinyint] NULL,
	[BirthMonth] [tinyint] NULL,
	[BirthYear] [smallint] NULL,
	[UserName] [nvarchar](255) NULL,
	[Gender] [nchar](6) NULL,
	[Locale] [nvarchar](255) NULL,
	[UserTimezone] [int] NULL,
	[About] [text] NULL,
	[Bio] [text] NULL,
	[Quotes] [text] NULL,
	[Hometown] [int] NULL,
	[Location] [int] NULL,
	[InterestedIn] [nvarchar](255) NULL,
	[MeetingFor] [nvarchar](255) NULL,
	[Political] [nvarchar](255) NULL,
	[Religion] [nvarchar](255) NULL,
	[RelationshipStatus] [nvarchar](255) NULL,
	[SignificantOther] [int] NULL,
	[Verified] [bit] NULL
)

